server:
  port: 8099
spring:
  application:
    name: ser_client
  datasource:
    hikari:
      username: root
      password: toor
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
    url: jdbc:mysql://192.168.218.130:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.218.130:8088/eureka/