server:
  port: 8080
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.52:8088/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'