server:
  port: 8101
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.223.129:8088/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'