server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.52:8088/eureka/

spring:
  application:
    name: config_server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/cnf
        bootstrap: true

